---
development:
  cloud_name: mobeeas-com
  api_key: '162321622739299'
  api_secret: Hdt1srTEiaZ0w-xF8I0UNzEQrzQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: mobeeas-com
  api_key: '162321622739299'
  api_secret: Hdt1srTEiaZ0w-xF8I0UNzEQrzQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: mobeeas-com
  api_key: '162321622739299'
  api_secret: Hdt1srTEiaZ0w-xF8I0UNzEQrzQ
  enhance_image_tag: true
  static_image_support: false
